### ISSUE TITLE
Standardize tours

### ISSUE THREAD

**Issue by LTLA** [LTLA/iSEE2018#11]
Some standardization of the formatting of the tours is necessary. 

- Bold should be reserved for whatever actions you want the user to take. Using **Action:** makes sense and forces the reader to pay attention.
- Italics should be reserved for words in the app that you want people to look at, or to select.

**Comment by LTLA** [comment]
Is this closeable?

**Comment by kevinrue** [comment]
Forgot to push my update on `tourtour`. Incoming: ba490a59149f06600443b3cc2493fc24949331f8
